# Generated by Django 5.0.6 on 2024-05-14 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moose', '0004_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
